dist: focal
language: nodejs
node_js:
- lts/*
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_b295e0f06079_key -iv $encrypted_b295e0f06079_iv
  -in gaekey.json.enc -out gaekey.json -d
- bash docker-init.sh
deploy:
  provider: gae
  keyfile: gaekey.json
  project: "<Project-ID>"
  on:
    branch: main
jobs:
  include:
  - stage: test
  - stage: deploy
    script: bash docker_push.sh
env:
  global:
  - secure: Cdv65P/Z4KDkD88FHt9P0yRmGnD12JC24ccCItLz7YJL3EpF4ClvOneg2IHjsKBNqhITVqCpIDgPxALeD6J1srA4jBrIPtJ58qXSaxAO7bZntX4T8vFbvgz0KOA4kEehG9eT7ihmPq95eptqhr6k0TAWZYB0Jw6uvE5a8e6D8mGfq/w+bEqqv86X8Z8lmbdJF1mWQBtqElhkZ5nFOq4gFPwGQa9hAwceakENLgJomSGNjf44P/AEAr+TjUOnSW7D+Dj6Bc32TH5GcOSpXDqGoG/qCiay0hDHmX6TaxF7vRjFgkayDcTS10LDP1XqHnhoZZSFBUt/6209uA+dwFDzQtelp3f+5nyP7BDvdu/PVmioi/SH2SbWioPunc8HvKdh6KiuPaX5NSlsWwkkp0bJnA1Dtgh/IIA17PHz0ExrS7/KAW5hDqvg0Kc3C941Y4kzCRoERRS7Cbc5oU58MrOg8j09b9VFzyvFlE/IrvAirJ7paBrOkdEt4ML6WcEBlcGlDSTBGAJPaY9zmAwVsxqDTcMvDenxdojDbpmDPXO121g29IDlgMhB0wXpCExsjZt6VwvrCj7+ZwO2X2uvhAPqSl26i3nAdGCmudVuQY0We04ysPv9LCYZ6eVKX5LSPNeS0JXFJPyqTdkEF4d/hP/F1faX/QP/+tdTN5ybCYBvcTY=
  - secure: j2dcvBZCTCh/wIc3Fi/uBD8bOruMBobQYLqbtOCfrj+I41a4APRubIHiZ+4V679c6FZ8YrUHifnMYyQEk36C9BydwHxLGuNVXPjWq+Q7SVj+f3SMsns7gQX2N9sUOFkXvSFnaZDCkEAWzUAUQ9AdjZwd0Fu4GaCS4B2B3lHWWbmhN+AQ+W7HHGt8RJIGpQLKJro7sdKsA7GabmedeO34A2yIqfsT+S+XNaQIth7UFXyuNM2Gbm/jCCESCA/VhhHzzqGcEM1rNSYWYaBb2/AvWL+T96ebwuSzfY9KsZVHqaerEtubfBqrwVUx2CxKMqEbPszVvbnhe5S3Yp6vy3vzkRcuBRFu/1RjPMEszQmVEzAOpnidPP+w079Y2BKt1O3gghFiK6FSPQ4Vd7lG5UaawwrdptceTXAxP+IKhzpZS53ejG/7k2tRd/IZ/fRzwhovf+3RTx7lj/aW2xddwDwgcI3jCpt0dBkh9oLq3Kjks5d5WB5p+YMgDfZf1UQlZdTUm8Ba0HrdlHJjQNwgCcQ71bKlsQ6UzF+4rUIWR2UJxmdkTRaIhav3VdaOyY9kCAPKwlIu0vj893vEjaaDbeFzAL4jClIhGhckl1T4Bld0dqTxRPlybVW7WwOdddGtt5wrXwcryRwV7iC/XpsiwDp1ReE2To6P0sIMAV2PIaIWm2Q=
